
    open_menu = option_menu(
        "Πηγές",
        ["Ριζοσπάστης - 902",
         "Oικονομικές σελίδες",
         "Γενικά",
         "Διεθνής Οικονομία",
         "Διεθνή", 
         "Παραπολιτικά",
         "Βουλή",
         "Ραδιόφωνα"
         ],
         orientation="horizontal",
         )

####### 

elif main_menu == "Πηγές":
    tab1, tab2, tab3, tab4, tab5, tab6, tab7, tab8 = st.tabs([
    "Ριζοσπάστης - 902",
    "Παραπολιτικά",
    "Βουλή",
    "Γενικά",
    "Οικονομικές σελίδες",
    "Διεθνής Οικονομία",
    "Διεθνή",
    "Ραδιόφωνα"
    ], width="stretch")

    with tab1:
        st.subheader("Ριζοσπάστης - 902")

        with st.expander("Διάλεξε για Ριζοσπάστη", expanded=True):

            if st.button("Δες τις κυριότερες ειδήσεις"):
                feed_read_rizospastis_streamlit()

            if st.button("Δες την Άποψη"):
                rizos_apopsi()

            if st.button("Σώσε σε ΒΔ"):
                feed_to_R_db()

            if st.button("ΒΔ Ριζοσπάστης"):
                show_R_DB_streamlit()
            

    with tab2:
        st.subheader("Παραπολιτικά")
        read_parapolitika_all_streamlit()

    with tab3:
        st.subheader("Βουλή")

        # Δημιουργούμε ένα dropdown menu για επιλογές μέσα στο tab
        choice = st.selectbox("Επέλεξε μια ενέργεια", [
            "Το πρόγραμμα της Βουλής",
            "vouliwatch",
            "Πρακτικά"
        ])

        if choice == "Το πρόγραμμα της Βουλής":
            rn_vouli()
        elif choice == "vouliwatch":
            webbrowser.open("https://vouliwatch.gr/news")
        elif choice == "Πρακτικά":
            webbrowser.open("https://www.hellenicparliament.gr/Praktika/Synedriaseis-Olomeleias")


    with tab4:
        st.subheader("Γενικά")
        rn_show_general_news()

    with tab5:
        st.subheader("Οικονομικές Σελίδες")
        rn_show_greek_economy_news_buttons()

    with tab6:
        st.subheader("Διεθνής Οικονομία")
        rn_global_economy_news_buttons()
        feed_google_news_streamlit()

    with tab7:
        st.subheader("Διεθνή")

        with st.expander("Επέλεξε για Διεθνή"):
            rn_show_diethni_news()
            rn_show_geopolitics_news()
            rn_show_brics_news()

    with tab8:
        with st.subheader("Ραδιόφωνα"):
            rn_radios()